### ISSUE TITLE
DomainFileStoreService.CheckAllowedAccordingToIsHidden throws exception where it should not

### ISSUE THREAD

**Issue by samatstariongroup** [STARIONGROUP/COMET-WebServices-Community-Edition#213]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET Web Services
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-WebServices-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-WebServices-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The `DomainFileStoreService.CheckAllowedAccordingToIsHidden` method throws an `System.Exception`. Some issues with this:
  - we should not be throwing `System.Exception`, better to throw something like a `AuthorizationException`
  - or we don't throw an exception but we return a boolean (true or false) => this is the preferred approach

- [ ] Make change, start with returning a boolean.
- [ ] Check if the changes result in a logical user experience in the IME.
- [ ] Check DomainFileStore Integration tests

### Steps to Reproduce
NA

### System Configuration
- COMET Web Services version: 6.1.4
-

**Comment by samatrhea** [comment]
@lxatrhea can you check wheter this is still an issue?
