### ISSUE TITLE
Problem connecting to deployed COMET server through COMET IME

### ISSUE THREAD

**Issue by f-ferrari** [STARIONGROUP/COMET-WebServices-Community-Edition#347]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET Web Services
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-WebServices-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-WebServices-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I have set up a COMET server on an Ubuntu 22.04 machine, following the instructions provided at https://comet.io.esa.int/content/8-setup/00-index.html.
All relevant tests pass:
- docker ps -a -> shows the two COMET processes running
- curl localhost:5000 -> shows the page html file
- sudo nginx -t -> tests are succesful
- sudo systemctl restart nginx; sudo systemctl status nginx -> nginx is active
- https://[SERVERIP]:443 -> shows the welcome page, even in other machines in the local network; however, the browser says that the certificate is not valid (it is a self-signed certificate).
- https://[SERVERIP]:443/SiteDirectory -> returns the JSON file, even in other machines in the local network

When I try to connect to the Server via the COMET IME (from other machines), using https://[SERVERIP]:443, https://[SERVERIP], https://[SERVERIP]:5000, none of these allow me to connect. Could this correlated with the self-signed certificate? Or, how can i troubleshoot/solve this issue?

**Comment by samatstariongroup** [comment]
we have just made an improvement in the SDK that solves the problem. We are working on version 10 in which this will be included. Can you please use version 4.1.0.0 of the web-app and check whether with the fulltrust option enabled you can access the server? You can deploy the web app as a docker container or use the starion hosted one at https://comet-web.cdp4.org/

**Comment by lxatstariongroup** [comment]
Fixed in web-app 4.1.0 and IME 10.0.0-RC12.
